### ISSUE TITLE
bug if deleting backwards during auto completion:

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-postfix#180]
there is a bug if deleting backwards during auto completion:
![2022-11-02 18-10-41 2022-11-02 18_11_24](https://user-images.githubusercontent.com/6239652/199463093-424f2f06-1102-4f84-aa76-fffb79f770b9.gif)

__Originally posted by @daya0576 in https://github.com/fannheyward/coc-postfix/pull/179#issuecomment-1300237405__

**Comment by fannheyward** [comment]
@daya0576 I can't reproduce this.

**Comment by daya0576** [comment]
> @daya0576 I can't reproduce this.

Hi, here are steps to reproduce this issue:
1. install `coc-postfix@0.1.0`
2. trigger `LS` completion
3. keep typing few characters
4. delete backward(but keep one character left)
5. trigger `Postfix` auto completion
6. enter

![2022-11-03 10 48 02](https://user-images.githubusercontent.com/6239652/199638794-b57843c2-bf2a-463c-bc2c-59747da603cd.gif)

**Comment by daya0576** [comment]
@fannheyward when debugging the code below:
https://github.com/fannheyward/coc-postfix/blob/152d24b7926351712bcb466abfaaf67e7ed1ac22/src/completionItemBuilder.ts#L15-L32

the value of variable `position`:
- `(2, 2)` | working correctly: 
- `(2, 4)` | bug if deleting backwards:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/6239652/199661800-203cd595-867e-4e5c-99c5-54f5e318e950.png">

**Comment by fannheyward** [comment]
Reproduced, will look into this.

**Comment by fannheyward** [comment]
Try v0.1.1
