### ISSUE TITLE
Postfix await

### ISSUE THREAD

**Issue by weirongxu** [fannheyward/coc-postfix#7]
Hello, thank you for creating this extension.

Have you considered implementing intelligent postfix?
For example, use AST to parse Typescript, so as to implement the await of the postfix, just like rust.

```typescript
const response = (await fetch('url')).json().await|
```

to

```typescript
const response = await (await fetch('url')).json()
```

**Comment by fannheyward** [comment]
AST is not used currently, I'll add it later.

**Comment by weirongxu** [comment]
tsserver already supports a similar feature, this is not required
