### ISSUE TITLE
Completion popup doesn't show when inside a function call

### ISSUE THREAD

**Issue by mnrce** [fannheyward/coc-postfix#71]
As mentioned in https://github.com/neoclide/coc.nvim/issues/1741, when I'm inside a function call with coc-postfix enabled, the completion popup doesn't show up, even when I triggered it using <kbd>ctrl-space</kbd>. The completion popup shows up again after I've disabled coc-postfix.

GIF:
![a](https://user-images.githubusercontent.com/13317164/80107987-fc775b00-85a5-11ea-95ba-4192d19565f2.gif)

I'm using:
* coc-postfix 0.0.8
* NVIM v0.5.0-436-ge8269a3ab
* https://github.com/neoclide/coc.nvim/commit/0d4f02555e5aaecbd8efef47a70ba2f2c6412d1f

**Comment by fannheyward** [comment]
cic-postfix 0.0.9 has released with a quick fix for this, I'll continue to improve this.
